version: '2'

services: 
  php:
    build: 
      context: .
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_HOST=$DB_HOST
        - JWT_SECRET=$JWT_SECRET
        - BASE_URL= $BASE_URL
        - RELAXED=$RELAXED
        - MIDDLE_URL=$MIDDLE_URL
    expose: 
      - "80"
  mysql: 
    image: mysql:5.6.23
    env_file:
      - .env


